// Mock data for serverless API routes

export const mockCategories = [
  {
    id: '1',
    name: 'Mattresses',
    slug: 'mattresses',
    description: 'Premium mattresses for every sleep style',
    image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800',
    productCount: 5,
  },
  {
    id: '2',
    name: 'Bedding',
    slug: 'bedding',
    description: 'Luxury sheets, pillows, and comforters',
    image: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800',
    productCount: 4,
  },
  {
    id: '3',
    name: 'Electronics',
    slug: 'electronics',
    description: 'Smart home devices and electronics',
    image: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800',
    productCount: 4,
  },
  {
    id: '4',
    name: 'Furniture',
    slug: 'furniture',
    description: 'Bedroom and living room furniture',
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800',
    productCount: 3,
  },
];

export const mockProducts = [
  // Mattresses
  {
    id: '1',
    name: 'CloudRest Memory Foam Mattress',
    slug: 'cloudrest-memory-foam-mattress',
    description: 'Experience the ultimate in comfort with our CloudRest Memory Foam Mattress. Featuring advanced cooling gel technology and multiple layers of premium memory foam for perfect pressure relief.',
    shortDescription: 'Premium memory foam with cooling gel technology',
    sku: 'MATT-001',
    price: 899.99,
    compareAtPrice: 1199.99,
    costPrice: 450,
    images: ['https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800'],
    categoryId: '1',
    category: { id: '1', name: 'Mattresses', slug: 'mattresses' },
    stock: 25,
    lowStockThreshold: 5,
    weight: 75,
    dimensions: { length: 80, width: 60, height: 12 },
    tags: ['memory foam', 'cooling', 'queen'],
    isActive: true,
    isFeatured: true,
    rating: 4.8,
    reviewCount: 324,
  },
  {
    id: '2',
    name: 'DreamLux Hybrid Mattress',
    slug: 'dreamlux-hybrid-mattress',
    description: 'The DreamLux Hybrid combines the best of innerspring support with memory foam comfort. Perfect for couples with different sleep preferences.',
    shortDescription: 'Hybrid design with innerspring and memory foam',
    sku: 'MATT-002',
    price: 1299.99,
    compareAtPrice: 1599.99,
    costPrice: 650,
    images: ['https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800'],
    categoryId: '1',
    category: { id: '1', name: 'Mattresses', slug: 'mattresses' },
    stock: 18,
    lowStockThreshold: 5,
    weight: 85,
    dimensions: { length: 80, width: 76, height: 14 },
    tags: ['hybrid', 'king', 'couples'],
    isActive: true,
    isFeatured: true,
    rating: 4.9,
    reviewCount: 256,
  },
  {
    id: '3',
    name: 'EcoSleep Organic Latex Mattress',
    slug: 'ecosleep-organic-latex-mattress',
    description: 'Made with 100% organic latex and natural materials, the EcoSleep is perfect for eco-conscious sleepers who don\'t want to compromise on comfort.',
    shortDescription: '100% organic latex, naturally hypoallergenic',
    sku: 'MATT-003',
    price: 1599.99,
    compareAtPrice: 1999.99,
    costPrice: 800,
    images: ['https://images.unsplash.com/photo-1556656793-08538906a9f8?w=800'],
    categoryId: '1',
    category: { id: '1', name: 'Mattresses', slug: 'mattresses' },
    stock: 12,
    lowStockThreshold: 3,
    weight: 90,
    dimensions: { length: 80, width: 60, height: 10 },
    tags: ['organic', 'latex', 'eco-friendly'],
    isActive: true,
    isFeatured: false,
    rating: 4.7,
    reviewCount: 189,
  },
  // Bedding
  {
    id: '4',
    name: 'Egyptian Cotton Sheet Set',
    slug: 'egyptian-cotton-sheet-set',
    description: 'Luxurious 1000 thread count Egyptian cotton sheets. Includes fitted sheet, flat sheet, and 2 pillowcases.',
    shortDescription: '1000 thread count Egyptian cotton',
    sku: 'BED-001',
    price: 249.99,
    compareAtPrice: 349.99,
    costPrice: 100,
    images: ['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800'],
    categoryId: '2',
    category: { id: '2', name: 'Bedding', slug: 'bedding' },
    stock: 50,
    lowStockThreshold: 10,
    weight: 5,
    dimensions: { length: 14, width: 12, height: 4 },
    tags: ['sheets', 'egyptian cotton', 'luxury'],
    isActive: true,
    isFeatured: true,
    rating: 4.6,
    reviewCount: 412,
  },
  {
    id: '5',
    name: 'Memory Foam Pillow Set',
    slug: 'memory-foam-pillow-set',
    description: 'Set of 2 premium shredded memory foam pillows with cooling bamboo covers. Adjustable fill for perfect comfort.',
    shortDescription: 'Adjustable shredded memory foam, set of 2',
    sku: 'BED-002',
    price: 89.99,
    compareAtPrice: 129.99,
    costPrice: 35,
    images: ['https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=800'],
    categoryId: '2',
    category: { id: '2', name: 'Bedding', slug: 'bedding' },
    stock: 75,
    lowStockThreshold: 15,
    weight: 4,
    dimensions: { length: 20, width: 26, height: 6 },
    tags: ['pillows', 'memory foam', 'cooling'],
    isActive: true,
    isFeatured: false,
    rating: 4.5,
    reviewCount: 567,
  },
  {
    id: '6',
    name: 'Down Alternative Comforter',
    slug: 'down-alternative-comforter',
    description: 'Plush, hypoallergenic down alternative comforter. All-season weight with corner tabs for duvet cover attachment.',
    shortDescription: 'Hypoallergenic, all-season comfort',
    sku: 'BED-003',
    price: 149.99,
    compareAtPrice: 199.99,
    costPrice: 60,
    images: ['https://images.unsplash.com/photo-1616627561839-074385245ff6?w=800'],
    categoryId: '2',
    category: { id: '2', name: 'Bedding', slug: 'bedding' },
    stock: 40,
    lowStockThreshold: 8,
    weight: 8,
    dimensions: { length: 90, width: 90, height: 3 },
    tags: ['comforter', 'hypoallergenic', 'all-season'],
    isActive: true,
    isFeatured: false,
    rating: 4.4,
    reviewCount: 234,
  },
  // Electronics
  {
    id: '7',
    name: 'Premium 4K Smart TV 65"',
    slug: 'premium-4k-smart-tv-65',
    description: 'Stunning 65-inch 4K UHD Smart TV with HDR10+, Dolby Vision, and built-in streaming apps. Crystal clear picture quality.',
    shortDescription: '65" 4K UHD with HDR10+ and Dolby Vision',
    sku: 'ELEC-001',
    price: 1299.99,
    compareAtPrice: 1599.99,
    costPrice: 750,
    images: ['https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800'],
    categoryId: '3',
    category: { id: '3', name: 'Electronics', slug: 'electronics' },
    stock: 15,
    lowStockThreshold: 3,
    weight: 55,
    dimensions: { length: 58, width: 34, height: 4 },
    tags: ['tv', '4k', 'smart tv', 'entertainment'],
    isActive: true,
    isFeatured: true,
    rating: 4.7,
    reviewCount: 892,
  },
  {
    id: '8',
    name: 'Smart Home Speaker System',
    slug: 'smart-home-speaker-system',
    description: 'Premium wireless speaker system with voice assistant, multi-room audio support, and incredible bass response.',
    shortDescription: 'Voice-controlled multi-room audio',
    sku: 'ELEC-002',
    price: 349.99,
    compareAtPrice: 449.99,
    costPrice: 150,
    images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800'],
    categoryId: '3',
    category: { id: '3', name: 'Electronics', slug: 'electronics' },
    stock: 30,
    lowStockThreshold: 5,
    weight: 8,
    dimensions: { length: 8, width: 8, height: 12 },
    tags: ['speaker', 'smart home', 'audio'],
    isActive: true,
    isFeatured: false,
    rating: 4.5,
    reviewCount: 456,
  },
  {
    id: '9',
    name: 'Gaming Console Pro',
    slug: 'gaming-console-pro',
    description: 'Next-gen gaming console with 4K gaming at 120fps, ray tracing, and 1TB SSD storage. Includes wireless controller.',
    shortDescription: '4K gaming at 120fps with ray tracing',
    sku: 'ELEC-003',
    price: 499.99,
    compareAtPrice: null,
    costPrice: 400,
    images: ['https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=800'],
    categoryId: '3',
    category: { id: '3', name: 'Electronics', slug: 'electronics' },
    stock: 8,
    lowStockThreshold: 2,
    weight: 10,
    dimensions: { length: 15, width: 12, height: 4 },
    tags: ['gaming', 'console', '4k'],
    isActive: true,
    isFeatured: true,
    rating: 4.9,
    reviewCount: 1234,
  },
  {
    id: '10',
    name: 'Wireless Noise-Canceling Headphones',
    slug: 'wireless-noise-canceling-headphones',
    description: 'Premium over-ear headphones with active noise cancellation, 30-hour battery life, and studio-quality sound.',
    shortDescription: 'ANC headphones with 30hr battery',
    sku: 'ELEC-004',
    price: 279.99,
    compareAtPrice: 349.99,
    costPrice: 120,
    images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800'],
    categoryId: '3',
    category: { id: '3', name: 'Electronics', slug: 'electronics' },
    stock: 45,
    lowStockThreshold: 10,
    weight: 1,
    dimensions: { length: 8, width: 7, height: 4 },
    tags: ['headphones', 'wireless', 'noise-canceling'],
    isActive: true,
    isFeatured: false,
    rating: 4.6,
    reviewCount: 678,
  },
  // Furniture
  {
    id: '11',
    name: 'Modern Platform Bed Frame',
    slug: 'modern-platform-bed-frame',
    description: 'Sleek, minimalist platform bed frame with built-in USB charging ports. Solid wood construction with premium finish.',
    shortDescription: 'Platform bed with USB charging ports',
    sku: 'FURN-001',
    price: 599.99,
    compareAtPrice: 799.99,
    costPrice: 280,
    images: ['https://images.unsplash.com/photo-1505693314120-0d443867891c?w=800'],
    categoryId: '4',
    category: { id: '4', name: 'Furniture', slug: 'furniture' },
    stock: 10,
    lowStockThreshold: 2,
    weight: 120,
    dimensions: { length: 83, width: 63, height: 14 },
    tags: ['bed frame', 'platform', 'modern'],
    isActive: true,
    isFeatured: true,
    rating: 4.7,
    reviewCount: 189,
  },
  {
    id: '12',
    name: 'Upholstered Headboard',
    slug: 'upholstered-headboard',
    description: 'Luxurious tufted upholstered headboard with premium fabric. Easy wall mount or bed frame attachment.',
    shortDescription: 'Tufted design with premium fabric',
    sku: 'FURN-002',
    price: 349.99,
    compareAtPrice: 449.99,
    costPrice: 150,
    images: ['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800'],
    categoryId: '4',
    category: { id: '4', name: 'Furniture', slug: 'furniture' },
    stock: 15,
    lowStockThreshold: 3,
    weight: 45,
    dimensions: { length: 64, width: 4, height: 54 },
    tags: ['headboard', 'upholstered', 'tufted'],
    isActive: true,
    isFeatured: false,
    rating: 4.5,
    reviewCount: 145,
  },
  {
    id: '13',
    name: 'Nightstand with Wireless Charging',
    slug: 'nightstand-wireless-charging',
    description: 'Modern nightstand with built-in wireless charging pad, USB ports, and soft-close drawer. Perfect bedroom companion.',
    shortDescription: 'Built-in wireless charging pad',
    sku: 'FURN-003',
    price: 249.99,
    compareAtPrice: 299.99,
    costPrice: 100,
    images: ['https://images.unsplash.com/photo-1532372320572-cda25653a26d?w=800'],
    categoryId: '4',
    category: { id: '4', name: 'Furniture', slug: 'furniture' },
    stock: 20,
    lowStockThreshold: 4,
    weight: 35,
    dimensions: { length: 22, width: 18, height: 24 },
    tags: ['nightstand', 'wireless charging', 'smart'],
    isActive: true,
    isFeatured: false,
    rating: 4.4,
    reviewCount: 98,
  },
];

// In-memory cart storage (will reset on each cold start)
const carts: Record<string, any> = {};

export function getCart(sessionId: string) {
  if (!carts[sessionId]) {
    carts[sessionId] = {
      id: sessionId,
      items: [],
      subtotal: 0,
      discountTotal: 0,
      taxTotal: 0,
      shippingTotal: 0,
      total: 0,
      itemCount: 0,
    };
  }
  return carts[sessionId];
}

export function updateCart(sessionId: string, cart: any) {
  carts[sessionId] = cart;
  return cart;
}

export function calculateCartTotals(cart: any) {
  const subtotal = cart.items.reduce((sum: number, item: any) => sum + item.totalPrice, 0);
  const taxTotal = subtotal * 0.08; // 8% tax
  const shippingTotal = subtotal >= 100 ? 0 : 9.99;
  const total = subtotal + taxTotal + shippingTotal - cart.discountTotal;
  const itemCount = cart.items.reduce((sum: number, item: any) => sum + item.quantity, 0);

  return {
    ...cart,
    subtotal,
    taxTotal,
    shippingTotal,
    total,
    itemCount,
  };
}

